name: Checkstyle
on: [push, pull_request]
    
jobs:
  checkstyle:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Checkstyle
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run Checkstyle
      uses: dbelyaev/action-checkstyle@v1.1.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: 'github-pr-check'
        level: error
        checkstyle_config: checkstyle.xml
